### ISSUE TITLE
Check if the Email is sent to address of matching of the condition

### ISSUE THREAD

**Issue by MasahiroAsaka** [b-eee/HncFunction#2]
・Check if the email is sent to the address of  **send_mail** data report of the workspace

・Remove this part
https://github.com/b-eee/HncFunction/blob/9308646bbff9cd180f600348c4e17cefd6f267ef/HNC%20Lockon%20Send%20Email/HncSendEmail.cs#L104
```
Name = itemDict["customer_name"].ToString()
```

**Comment by marwenbhz** [comment]
check this issue, for you want to check sending multiplle email, you see in your local , and change timer to execute send email batch.

**Comment by marwenbhz** [comment]
not send cause issue of apiikey, please check it, or will migrate template to our sendgrid account and make apikey and its working when i test, please check.
