### ISSUE TITLE
Chage mapping logic

### ISSUE THREAD

**Issue by MasahiroAsaka** [b-eee/HncFunction#8]
1. ~~the value of **lockon_type** which is getting form SAMDataPool when getBatch, 
when **lockon_type is 99**~~
　if **lockon_type** value in hexabase is **99**
　get organization_name tag value from SAMDATAPOOL using "organization_parent_seq" as the search key and put the value as "organization_parent_name" in lockon ds.
　get organization_code tag value from SAMDATAPOOL using "organization_parent_seq" as the search key and put the value as "organization_parent_code" in lockon ds.

~~**if lockon_type not 99**~~
　if it is not **99**
　　get "lockon_organization_name_company_print" value from SAMDATAPOOL and put the value as "organization_parent_name" in lockon ds.
　　get "lockon_organization_name_print" value from SAMDATAPOOL and put the value as "organization_name" in lockon ds.

2.  ~~**not sync lockon_type for Lockon ds in Hexabase**  (if it is synced now)~~
sync lockon_type for Lockon ds in Hexabase

**Comment by Hokutosei** [comment]
@MasahiroAsaka for this, the function name is this `GetBatch` ?

**Comment by MasahiroAsaka** [comment]
@Hokutosei  yes GetBtach
